### PR TITLE
Fixed object reference duplicate in arrays #19

### LINKED ISSUE #19: Collection editing
I have a list of SerializableInterface<>. 
Editing the value of one element in the list changes the value of all elements with the same type in that list.

```csharp
public class CombineStringsValue : MonoBehaviour, IProvideValue<string>
{
    [SerializeField] private List<SerializableInterface<IProvideValue<string>>> m_Providers;

    public string Value => m_Providers.Aggregate("", (current, provider) => current + provider.Value.Value);
}
```

image

### PR DESCRIPTION
**Pull request by marc-antoine-girard**
# Description

As described by the issue, when a new instance of **SerializableInterface<T>** is added in an array using the inspector's gizmo, Unity clones the last **SerializableInterface<T>**. Since rawReference is [SerializeReference], the reference of the object is copied by ref, which makes the new element references the same instance as the previous one. 

**Editing the last element will modify the previous one too.** 

This bug should only applies to pure serializable C# classes stored in the **rawReference**'s field. This is why I moved the fix from SerializableInterfacePropertyDrawer to  RawReferenceDrawer in my previous commits. 

**This fixes #19** without adding any dependencies and in an _easy-to read (ish)_ fashion.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project (added first constants, had to guess the naming convention)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

**Unrelated Note**: Unless I'm missing something,  the ReferenceDrawer instantiated in GetReferenceDrawer(..) could be reused for every instances, the same way Unity reuses the PropertyDrawer for multiple instances to avoid GC.

### CODE REVIEW

File: Editor/Drawers/RawReferenceDrawer.cs [hunk 1]
```diff
@@ -91,5 +107,37 @@ protected override void OnPropertiesClicked()
...
         }
+
+        private void AvoidDuplicateReferencesInArray()
+        {
+            if (!IsPropertyInArray(Property)) return;
+            if (previousPropertyPath == null) return;
+            if (previousPropertyPath == Property.propertyPath) return;
+
+            var rawReferenceProperty = Property.FindPropertyRelative("rawReference");
+            var currentReferenceValue = RawReferenceValue;
```
Comment (Thundernerd) [inline Editor/Drawers/RawReferenceDrawer.cs:118]: Please change to explicit types :)

File: Editor/Drawers/RawReferenceDrawer.cs [hunk 2]
```diff
@@ -91,5 +107,37 @@ protected override void OnPropertiesClicked()
...
+        }
+
+        private static bool IsPropertyInArray(SerializedProperty prop)
+        {
+            return prop.propertyPath.Contains(".Array.data[");
+        }
+
+        private static object CreateInstance(object source)
+        {
+            var instance = Activator.CreateInstance(source.GetType());
```
Comment (Thundernerd) [inline Editor/Drawers/RawReferenceDrawer.cs:138]: Please change to explicit types :)

File: Editor/Drawers/RawReferenceDrawer.cs [hunk 3]
```diff
@@ -91,5 +107,37 @@ protected override void OnPropertiesClicked()
...
+            EditorUtility.CopySerializedManagedFieldsOnly(source, instance);
+            return instance;
+        }
     }
-}
+}
```
Comment (Thundernerd) [inline Editor/Drawers/RawReferenceDrawer.cs:143]: Please add a newline at the end of the file :)

File: Editor/SerializableInterfacePropertyDrawer.cs [hunk 4]
```diff
@@ -108,4 +106,4 @@ GUIContent label
             }
         }
     }
-}
+}
```
Comment (Thundernerd) [inline Editor/SerializableInterfacePropertyDrawer.cs:109]: Please add a newline at the end of the file :)

File: Editor/SerializableInterfacePropertyDrawer.cs [hunk 5]
```diff
@@ -29,6 +26,7 @@ private void Initialize(SerializedProperty property)
             activeDrawer = null;
             serializedProperty = property;
             genericType = GetGenericArgument();
+
```
Comment (Thundernerd) [inline Editor/SerializableInterfacePropertyDrawer.cs:29]: Could you explain the reason for this added blank line?

File: Editor/Drawers/RawReferenceDrawer.cs [hunk 6]
```diff
@@ -91,5 +107,37 @@ protected override void OnPropertiesClicked()
                 }
             }
         }
+
+        private void AvoidDuplicateReferencesInArray()
+        {
+            if (!IsPropertyInArray(Property)) return;
+            if (previousPropertyPath == null) return;
+            if (previousPropertyPath == Property.propertyPath) return;
```
Comment (Thundernerd) [inline Editor/Drawers/RawReferenceDrawer.cs:115]: Please move the return to a new line :)

File: Editor/Drawers/RawReferenceDrawer.cs [hunk 7]
```diff
@@ -91,5 +107,37 @@ protected override void OnPropertiesClicked()
...
+
+            var rawReferenceProperty = Property.FindPropertyRelative("rawReference");
+            var currentReferenceValue = RawReferenceValue;
+
+            if (currentReferenceValue == null) return;
```
Comment (Thundernerd) [inline Editor/Drawers/RawReferenceDrawer.cs:120]: Please move the return to a new line :)

File: Editor/Drawers/RawReferenceDrawer.cs [hunk 8]
```diff
@@ -11,6 +11,9 @@ internal class RawReferenceDrawer : ReferenceDrawer, IReferenceDrawer
         private readonly GUIContent label;
         private readonly FieldInfo fieldInfo;
 
+        private static object previousReferenceValue;
+        private static string previousPropertyPath;
```
Comment (Thundernerd) [inline Editor/Drawers/RawReferenceDrawer.cs:15]: Could you explain the reason for making this static?

**Review by Thundernerd — CHANGES_REQUESTED** [review]
Thank you for the PR! I've added some questions and some formatting change requests, but can't blame you for that since I haven't specified the formatting anywhere :)

**Comment by Thundernerd** [comment]
> Unrelated Note: Unless I'm missing something, the ReferenceDrawer instantiated in GetReferenceDrawer(..) could be reused for every instances, the same way Unity reuses the PropertyDrawer for multiple instances to avoid GC.

Ah I hadn't thought about that. Might be interesting to take a look at! I'll add that to the list

File: Editor/Drawers/RawReferenceDrawer.cs (hunk 8 above)
Comment (marc-antoine-girard) [reply Editor/Drawers/RawReferenceDrawer.cs:15]: It used to be a local variable in SerializableInterfacePropertyDrawer.cs. The goal was to store the last element and check if the new element's rawReference object points to the same instance as the previous one. If it does AND this isn't actually the same variable (we know that using the propertyPath, see line 115 in RawReferenceDrawer.cs), then we need to create a new instance and reassign the values (line 124 - 125 in RawReferenceDrawer.cs). I've moved the code to RawReferenceDrawer.cs since it made more sense because it only applies to rawReferences, but since we always create a new instance for that drawer, we either need to pass the values of the previous object to its constructor, or save it in a static variable. 

Passing it using the constructor would also add unnecessary code in SerializableInterfacePropertyDrawer.cs. So the static way made sense in that regard. I hope it clears up things a bit. Also, it wouldn't need to be static if the instance of ReferenceDrawers where reused :)

**Comment by marc-antoine-girard** [comment]
I'm doing the changes and update the PR, thanks for your comments. This also is my first contribution on Github, so I'm still learning! :)

File: Editor/SerializableInterfacePropertyDrawer.cs (hunk 5 above)
Comment (marc-antoine-girard) [reply Editor/SerializableInterfacePropertyDrawer.cs:29]: It seems my Rider thought it looked better :) I'll remove it!

**Comment by marc-antoine-girard** [comment]
@Thundernerd Also, in `RawReferenceDrawer.cs`, you have this property, `RawReferenceValue` from which I added a setter. 
From what I understand, `managedReferenceValue` didn't exist in earlier version of Unity? If that's the case, in `ReferenceDrawer.cs`, `managedReferenceValue` is used everywhere. It might be worth moving the property to its base class. :)

**Review by Thundernerd — APPROVED** [review]
